services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCmsPagePlugin\:
        resource: '../../*'

    MonsieurBiz\SyliusCmsPagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    
    # Let's try to find the locale one more time!
    MonsieurBiz\SyliusCmsPagePlugin\Context\LastChanceLocaleContext:
        tags:
            - { name: sylius.context.locale, priority: -127 }

    # Menu item in admin panel
    MonsieurBiz\SyliusCmsPagePlugin\Listener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Page Forms
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page_translation.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\BlocType:
        arguments:
            $dataClass: '%monsieurbiz_cms_bloc.model.bloc.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\BlocTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_bloc.model.bloc_translation.class%'
            $validationGroups: ['monsieurbiz']

    # Routing Context
    MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext:
        decorates: router.request_context
        arguments: ['@MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext.inner']
