services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCmsPagePlugin\:
        resource: '../../*'

    MonsieurBiz\SyliusCmsPagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Menu item in admin panel
    MonsieurBiz\SyliusCmsPagePlugin\Listener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Page Forms
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page.class%'
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page_translation.class%'

    # Fixtures
    MonsieurBiz\SyliusCmsPagePlugin\Fixture\PageFixture:
        arguments:
            $exampleFactory: '@MonsieurBiz\SyliusCmsPagePlugin\Fixture\Factory\PageFixtureFactory'

    # Routing Context
    MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext:
        decorates: router.request_context
        arguments: ['@MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext.inner']
